import sharp from "sharp";
import fs from "fs";
import path from "path";

const ROOT_DIR = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT_DIR, "public");
const ICONS_DIR = path.join(PUBLIC_DIR, "assets/imgs/heroes/icons");
const PORTRAITS_DIR = path.join(PUBLIC_DIR, "assets/imgs/heroes/portraits");
const ROLES_DIR = path.join(PUBLIC_DIR, "assets/imgs/roles");
const OUTPUT_DIR = path.join(PUBLIC_DIR, "assets/imgs/heroes");
const ROLES_OUTPUT_DIR = path.join(PUBLIC_DIR, "assets/imgs/roles");
const SPRITE_MAP_PATH = path.join(ROOT_DIR, "src/data/spriteMap.ts");

const COLUMNS = 10;

const heroKeys = fs
  .readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.replace(".webp", ""))
  .sort();

async function generateSprite(
  inputDir: string,
  outputPath: string,
  cellWidth: number,
  cellHeight: number,
) {
  const rows = Math.ceil(heroKeys.length / COLUMNS);
  const composites = heroKeys.map((key, i) => ({
    input: path.join(inputDir, `${key}.webp`),
    left: (i % COLUMNS) * cellWidth,
    top: Math.floor(i / COLUMNS) * cellHeight,
  }));

  await sharp({
    create: {
      width: COLUMNS * cellWidth,
      height: rows * cellHeight,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .webp({ quality: 85 })
    .toFile(outputPath);

  console.log(`Generated: ${outputPath}`);
}

const roleKeys = ["tank", "damage", "support"];

async function generateRoleSprite(
  inputDir: string,
  outputPath: string,
  cellWidth: number,
  cellHeight: number,
) {
  const composites = roleKeys.map((key, i) => ({
    input: path.join(inputDir, `${key}.webp`),
    left: i * cellWidth,
    top: 0,
  }));

  await sharp({
    create: {
      width: roleKeys.length * cellWidth,
      height: cellHeight,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(composites)
    .webp({ quality: 85 })
    .toFile(outputPath);

  console.log(`Generated: ${outputPath}`);
}

async function generateSpriteMap() {
  const totalRows = Math.ceil(heroKeys.length / COLUMNS);

  const positions = heroKeys
    .map((key, i) => {
      const col = i % COLUMNS;
      const row = Math.floor(i / COLUMNS);
      return `  ${key}: { col: ${col}, row: ${row} }`;
    })
    .join(",\n");

  const rolePositions = roleKeys
    .map((key, i) => `  ${key}: { col: ${i}, row: 0 }`)
    .join(",\n");

  const content = `// Auto-generated by scripts/generate-sprites.ts -- do not edit manually

export const ICON_SPRITE = {
  src: "/assets/imgs/heroes/hero-icons-sprite.webp",
  columns: ${COLUMNS},
  rows: ${totalRows},
} as const;

export const PORTRAIT_SPRITE = {
  src: "/assets/imgs/heroes/hero-portraits-sprite.webp",
  columns: ${COLUMNS},
  rows: ${totalRows},
} as const;

export const ROLE_SPRITE = {
  src: "/assets/imgs/roles/role-icons-sprite.webp",
  columns: ${roleKeys.length},
  rows: 1,
} as const;

export const spritePositions: Record<string, { col: number; row: number }> = {
${positions},
};

export const roleSpritePositions: Record<string, { col: number; row: number }> = {
${rolePositions},
};
`;

  fs.writeFileSync(SPRITE_MAP_PATH, content);
  console.log(`Generated: ${SPRITE_MAP_PATH}`);
}

async function main() {
  await generateSprite(
    ICONS_DIR,
    path.join(OUTPUT_DIR, "hero-icons-sprite.webp"),
    95,
    85,
  );
  await generateSprite(
    PORTRAITS_DIR,
    path.join(OUTPUT_DIR, "hero-portraits-sprite.webp"),
    180,
    310,
  );
  await generateRoleSprite(
    ROLES_DIR,
    path.join(ROLES_OUTPUT_DIR, "role-icons-sprite.webp"),
    175,
    150,
  );
  await generateSpriteMap();

  console.log(
    `Done! ${heroKeys.length} heroes + ${roleKeys.length} roles processed.`,
  );
}

main();
