// Auto-generated by scripts/generate-sprites.ts -- do not edit manually

export const ICON_SPRITE = {
  src: "/assets/imgs/heroes/hero-icons-sprite.webp",
  columns: 10,
  rows: 5,
} as const;

export const PORTRAIT_SPRITE = {
  src: "/assets/imgs/heroes/hero-portraits-sprite.webp",
  columns: 10,
  rows: 5,
} as const;

export const ROLE_SPRITE = {
  src: "/assets/imgs/roles/role-icons-sprite.webp",
  columns: 3,
  rows: 1,
} as const;

export const spritePositions: Record<string, { col: number; row: number }> = {
  ana: { col: 0, row: 0 },
  anran: { col: 1, row: 0 },
  ashe: { col: 2, row: 0 },
  baptiste: { col: 3, row: 0 },
  bastion: { col: 4, row: 0 },
  brigitte: { col: 5, row: 0 },
  cassidy: { col: 6, row: 0 },
  domina: { col: 7, row: 0 },
  doomfist: { col: 8, row: 0 },
  dva: { col: 9, row: 0 },
  echo: { col: 0, row: 1 },
  emre: { col: 1, row: 1 },
  freja: { col: 2, row: 1 },
  genji: { col: 3, row: 1 },
  hanzo: { col: 4, row: 1 },
  hazard: { col: 5, row: 1 },
  illari: { col: 6, row: 1 },
  jetpackcat: { col: 7, row: 1 },
  junkerqueen: { col: 8, row: 1 },
  junkrat: { col: 9, row: 1 },
  juno: { col: 0, row: 2 },
  kiriko: { col: 1, row: 2 },
  lifeweaver: { col: 2, row: 2 },
  lucio: { col: 3, row: 2 },
  mauga: { col: 4, row: 2 },
  mei: { col: 5, row: 2 },
  mercy: { col: 6, row: 2 },
  mizuki: { col: 7, row: 2 },
  moira: { col: 8, row: 2 },
  orisa: { col: 9, row: 2 },
  pharah: { col: 0, row: 3 },
  ramattra: { col: 1, row: 3 },
  reaper: { col: 2, row: 3 },
  reinhardt: { col: 3, row: 3 },
  roadhog: { col: 4, row: 3 },
  sigma: { col: 5, row: 3 },
  sojourn: { col: 6, row: 3 },
  soldier76: { col: 7, row: 3 },
  sombra: { col: 8, row: 3 },
  symmetra: { col: 9, row: 3 },
  torbjorn: { col: 0, row: 4 },
  tracer: { col: 1, row: 4 },
  vendetta: { col: 2, row: 4 },
  venture: { col: 3, row: 4 },
  widowmaker: { col: 4, row: 4 },
  winston: { col: 5, row: 4 },
  wreckingball: { col: 6, row: 4 },
  wuyang: { col: 7, row: 4 },
  zarya: { col: 8, row: 4 },
  zenyatta: { col: 9, row: 4 },
};

export const roleSpritePositions: Record<string, { col: number; row: number }> =
  {
    tank: { col: 0, row: 0 },
    damage: { col: 1, row: 0 },
    support: { col: 2, row: 0 },
  };
