import { Hero } from '@/types/heroes';

export const heroesData: Record<string, Hero> = {
  dva: {
    name: 'D.Va',
    role: 'TANK',
    selected: false,
    key: 'dva',
  },
  orisa: {
    name: 'Orisa',
    role: 'TANK',
    selected: false,
    key: 'orisa',
  },
  reinhardt: {
    name: 'Reinhardt',
    role: 'TANK',
    selected: false,
    key: 'reinhardt',
  },
  roadhog: {
    name: 'Roadhog',
    role: 'TANK',
    selected: false,
    key: 'roadhog',
  },
  winston: {
    name: 'Winston',
    role: 'TANK',
    selected: false,
    key: 'winston',
  },
  wreckingball: {
    name: 'Wrecking Ball',
    role: 'TANK',
    selected: false,
    key: 'wreckingball',
  },
  zarya: {
    name: 'Zarya',
    role: 'TANK',
    selected: false,
    key: 'zarya',
  },
  doomfist: {
    name: 'Doomfist',
    role: 'TANK',
    selected: false,
    key: 'doomfist',
  },
  sigma: {
    name: 'Sigma',
    role: 'TANK',
    selected: false,
    key: 'sigma',
  },
  junkerqueen: {
    name: 'Junker Queen',
    role: 'TANK',
    selected: false,
    key: 'junkerqueen',
  },
  ramattra: {
    name: 'Ramattra',
    role: 'TANK',
    selected: false,
    key: 'ramattra',
  },
  mauga: {
    name: 'Mauga',
    role: 'TANK',
    selected: false,
    key: 'mauga',
  },
  hazard: {
    name: 'Hazard',
    role: 'TANK',
    selected: false,
    key: 'hazard',
  },
  bastion: {
    name: 'Bastion',
    role: 'DAMAGE',
    selected: false,
    key: 'bastion',
  },
  genji: {
    name: 'Genji',
    role: 'DAMAGE',
    selected: false,
    key: 'genji',
  },
  hanzo: {
    name: 'Hanzo',
    role: 'DAMAGE',
    selected: false,
    key: 'hanzo',
  },
  junkrat: {
    name: 'Junkrat',
    role: 'DAMAGE',
    selected: false,
    key: 'junkrat',
  },
  cassidy: {
    name: 'Cassidy',
    role: 'DAMAGE',
    selected: false,
    key: 'cassidy',
  },
  mei: {
    name: 'Mei',
    role: 'DAMAGE',
    selected: false,
    key: 'mei',
  },
  pharah: {
    name: 'Pharah',
    role: 'DAMAGE',
    selected: false,
    key: 'pharah',
  },
  reaper: {
    name: 'Reaper',
    role: 'DAMAGE',
    selected: false,
    key: 'reaper',
  },
  soldier76: {
    name: 'Soldier: 76',
    role: 'DAMAGE',
    selected: false,
    key: 'soldier76',
  },
  sombra: {
    name: 'Sombra',
    role: 'DAMAGE',
    selected: false,
    key: 'sombra',
  },
  symmetra: {
    name: 'Symmetra',
    role: 'DAMAGE',
    selected: false,
    key: 'symmetra',
  },
  torbjorn: {
    name: 'Torbjörn',
    role: 'DAMAGE',
    selected: false,
    key: 'torbjorn',
  },
  tracer: {
    name: 'Tracer',
    role: 'DAMAGE',
    selected: false,
    key: 'tracer',
  },
  widowmaker: {
    name: 'Widowmaker',
    role: 'DAMAGE',
    selected: false,
    key: 'widowmaker',
  },
  ashe: {
    name: 'Ashe',
    role: 'DAMAGE',
    selected: false,
    key: 'ashe',
  },
  echo: {
    name: 'Echo',
    role: 'DAMAGE',
    selected: false,
    key: 'echo',
  },
  sojourn: {
    name: 'Sojourn',
    role: 'DAMAGE',
    selected: false,
    key: 'sojourn',
  },
  venture: {
    name: 'Venture',
    role: 'DAMAGE',
    selected: false,
    key: 'venture',
  },
  freja: {
    name: 'Freja',
    role: 'DAMAGE',
    selected: false,
    key: 'freja',
  },
  ana: {
    name: 'Ana',
    role: 'SUPPORT',
    selected: false,
    key: 'ana',
  },
  brigitte: {
    name: 'Brigitte',
    role: 'SUPPORT',
    selected: false,
    key: 'brigitte',
  },
  lucio: {
    name: 'Lúcio',
    role: 'SUPPORT',
    selected: false,
    key: 'lucio',
  },
  mercy: {
    name: 'Mercy',
    role: 'SUPPORT',
    selected: false,
    key: 'mercy',
  },
  moira: {
    name: 'Moira',
    role: 'SUPPORT',
    selected: false,
    key: 'moira',
  },
  zenyatta: {
    name: 'Zenyatta',
    role: 'SUPPORT',
    selected: false,
    key: 'zenyatta',
  },
  baptiste: {
    name: 'Baptiste',
    role: 'SUPPORT',
    selected: false,
    key: 'baptiste',
  },
  kiriko: {
    name: 'Kiriko',
    role: 'SUPPORT',
    selected: false,
    key: 'kiriko',
  },
  lifeweaver: {
    name: 'Lifeweaver',
    role: 'SUPPORT',
    selected: false,
    key: 'lifeweaver',
  },
  illari: {
    name: 'Illari',
    role: 'SUPPORT',
    selected: false,
    key: 'illari',
  },
  juno: {
    name: 'Juno',
    role: 'SUPPORT',
    selected: false,
    key: 'juno',
  },
};
